### ISSUE TITLE
请问btrace支持的AGP有版本列表吗？

### ISSUE THREAD

**Issue by xiaobaDev** [bytedance/btrace#103]
AGP 4.2.2无法编译通过

**Comment by xiaomahuang** [comment]
> AGP 4.2.2无法编译通过

4.2.2是兼容过得，可以贴下具体报错的日志么

**Comment by treanow** [comment]
> > AGP 4.2.2无法编译通过
> 
> 4.2.2是兼容过得，可以贴下具体报错的日志么

预计啥时候兼容包AGP8.0

**Comment by xiaobaDev** [comment]
后来查了下是我们自己问题，具体原由忘了
