### ISSUE TITLE
Gradle project sync failed

### ISSUE THREAD

**Issue by Bingist** [bytedance/btrace#11]
I have git cloned btrace and open it using Android Studio, Gradle 6.7.1.
Then Gradle project sync failed with this message:

>A problem occurred configuring project ':app'.
> Could not create task ':app:minifyReleaseWithProguard'.
   > Cannot query the value of this provider because it has no value available.

What should I do to sync btrace with Gradle files successfully?

**Comment by qkmaosjtu** [comment]
Can you use debug to get more logs?

```
Run with the --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output
```

**Comment by Bingist** [comment]
Solved: https://stackoverflow.com/questions/64459937/could-not-create-task-appminifyreleasewithr8-cannot-query-the-value-of-this/65418056
