### ISSUE TITLE
生成的trace文件里面只有线程状态，其他什么都没有

### ISSUE THREAD

**Issue by shaomaicheng** [bytedance/btrace#123]
执行的命令是
```
 java -jar rhea-trace-processor-2.0.0.jar -a $包名 -t 10 -m  $mapping地址 -o output.pb rhea.all sched -fullClassName
```

![image](https://github.com/bytedance/btrace/assets/11388037/2afe48ac-4755-4c2b-bcb6-92c2a286498b)

**Comment by HunanDj** [comment]
@shaomaicheng 请问你解决了吗？我这里也有同样的问题。

**Comment by HunanDj** [comment]
@shaomaicheng 请问你解决了吗？我这里也有同样的问题。
