### ISSUE TITLE
btrace benchmark

### ISSUE THREAD

**Issue by JackyAndroid** [bytedance/btrace#15]
1. 性能消耗有没有具体数据？现在不能做到线上，差距还有多大？
2. 使用脚本抓取trace和不依赖PC抓取trace区别是？

_______
1. Do you have specific data on performance consumption? How big is the gap now with the online?
2. What is the difference between using script to capture trace and not relying on PC to capture trace?

**Comment by kissonchan** [comment]
> 

1. 性能数据只是在我们自己 App 测试启动场景，你们可以自己做benchmark，抖音启动性能损耗 < 10%，全量插桩，多线程采集情况下。
2. 依赖 PC 可以获取更多信息，比如cpu调度信息，ftrace 相关；不依赖 PC 就是后续线上使用的功能，只有 atrace 数据。

**Comment by JackyAndroid** [comment]
@kissonchan 达到线上使用要求，有计划表没？

**Comment by LNeway** [comment]
同一个方法是否开启 btrace差距有10倍，不开启时耗时2ms,开启之后开始 耗时20ms， 这个差距也有点太大了。

**Comment by mzule** [comment]
@LNeway 这个和该方法本身的子方法调用数量有关，因为在方法的开始与结束需要采集耗时信息，所以会有点性能损耗。此外，还有一些内存压力导致的GC损耗，这个在2.0.0已经优化了，可以体验看看。
