### ISSUE TITLE
 failed to write rhea-atrace.gz file completely

### ISSUE THREAD

**Issue by xinledanding** [bytedance/btrace#24]
![image](https://user-images.githubusercontent.com/19900856/155326996-27e24a4b-671a-46d3-b229-76ba6f1f64f6.png)
![image](https://user-images.githubusercontent.com/19900856/155327047-4567f984-5aeb-41bb-9185-9567abb83383.png)
![image](https://user-images.githubusercontent.com/19900856/155327123-4a6c0dea-0330-4d21-b481-d8d21eefb00c.png)
![image](https://user-images.githubusercontent.com/19900856/155327524-c169fb0d-9344-4ed9-bdff-78469606342b.png)

各种外置sdk操作quan权限都给了,还是不行,请问还需要配置啥

**Comment by wesley666** [comment]
如果启动app没看到初始化日志，你可能没有实现 Application.attachBaseContext，导致插入初始化代码失败 :
@Override
protected void attachBaseContext(Context base) {
    super.attachBaseContext(base);
}
