### ISSUE TITLE
不支持按 Enter 键盘停止

### ISSUE THREAD

**Issue by guangmomo** [bytedance/btrace#30]
`2022-03-12 16:46:26,447 - rhea_trace - main_impl - ERROR: - trace time must be specified or a non-negative number`

现在不支持按 Enter 键盘停止采集 trace 吗？
为什么文档里边写的是支持的。

**Comment by kevinStrange** [comment]
2022-07-07 15:23:16,228 - rhea_trace - main_impl - ERROR: - trace time must be specified or a non-negative number

**Comment by mzule** [comment]
应该是还没支持，文档已经更新了，我们将尽快支持。
