### ISSUE TITLE
 rhea_trace - main_impl - ERROR: - failed to write rhea-atrace.gz file completely

### ISSUE THREAD

**Issue by staringOrz** [bytedance/btrace#31]
已经确认集成了，并且已经打开了外部存储权限，但是就是显示失败

2022-03-18 18:51:21,220 - rhea_trace - main_impl - ERROR: - failed to write rhea-atrace.gz file completely.
2022-03-18 18:51:21,236 - rhea_trace - unzip_rhea_original_file - ERROR: - adb: error: failed to stat remote object 'sdcard/rhea-trace/xxxxx/rhea-atrace.gz': No such file or directory

WARM PROMPT
1. Make sure you have grant permission of writing external storage.
2. Make sure RheaTrace has been integrated into your app and inited successfully.
3. if `startWhenAppLaunch` is false, you can't capture trace when launch app.

**Comment by sunzhibindev** [comment]
me too

**Comment by gao746700783** [comment]
me too

**Comment by livelitoday** [comment]
我遇到了之后在应用详情里面手动打开了读写手机存储权限可以了

**Comment by wesley666** [comment]
如果启动app没看到btrace初始化日志，你可能没有实现 Application.attachBaseContext，导致插入初始化代码失败 :
@OverRide
protected void attachBaseContext(Context base) {
super.attachBaseContext(base);
}

**Comment by zhbzhbzhbz** [comment]
> @OverRide
> protected void attachBaseContext(Context base) {
> super.attachBaseContext(base);
> }

谢谢！！问题解决了
