### ISSUE TITLE
最新版platform-tools文件夹下没有systrace了

### ISSUE THREAD

**Issue by zhbzhbzhbz** [bytedance/btrace#38]
今天在Ubuntu上升级了platform-tools版本之后，遇到了`Can't find systrace in environment path`的问题，仔细一看platform-tools目录下的systrace目录没有了。解决方法分享给各位：
> 谷歌官方在22年3月发布的33.0.1版本的platform-tools包中移除了systrace，因此需要使用<=33.0.0的版本
<img width="423" alt="微信截图_20220607110213" src="https://user-images.githubusercontent.com/4599992/172296750-d978f0a3-65bd-4c73-ad96-845fdb04e88c.png">

33.0.0版本下载地址：
https://dl.google.com/android/repository/platform-tools_r33.0.0-linux.zip
https://dl.google.com/android/repository/platform-tools_r33.0.0-darwin.zip

转自：https://www.jianshu.com/p/626eaebaa6a8

**Comment by kingrukawa** [comment]
`$ python rheatrace.py -a {pkgName} -t 10 -o ./output/mynewtrace.html sched freq idle am wm gfx view binder_driver hal dalvik camera input res
Traceback (most recent call last):
  File "rheatrace.py", line 310, in <module>
    main_impl(sys.argv)
  File "rheatrace.py", line 233, in main_impl
    if not _initialize_devices(context):
  File "rheatrace.py", line 129, in _initialize_devices
    from devil.android.sdk import adb_wrapper
  File `"/Users/xxx/Library/Android/sdk/platform-tools/systrace/catapult/devil/devil/android/sdk/adb_wrapper.py",` line 21, in <module>
    import six
ImportError: No module named six`

33.0.0版本的platform-tools，脚本导包报错

**Comment by zhbzhbzhbz** [comment]
> 

这个好办呀，pip install six就行（注意要在python2环境下）

**Comment by kingrukawa** [comment]
> 

主要python都是门外汉，谢谢老哥

**Comment by kingrukawa** [comment]
> > 
> 
> 这个好办呀，pip install six就行（注意要在python2环境下）

主要python都是门外汉，谢谢老哥

**Comment by zzzxtnt** [comment]
这个命令在2.7下面安装 pip2 install --ignore-installed six
这个命令在3.x下面安装pip3 install --ignore-installed six

**Comment by mzule** [comment]
2.0.0 已经不再需要 systrace了
