### ISSUE TITLE
多线程：rhea-atrace.gz hasn't 'TRACE_END'

### ISSUE THREAD

**Issue by zhaoshuyu** [bytedance/btrace#39]
开启多线程记录情况下：输出trace文件时报错2022-06-07 20:29:23,587 - rhea_trace - unzip_rhea_original_file - WARNING: - sdcard/rhea-trace/XXX/rhea-atrace.gz hasn't 'TRACE_END'
查看原始文件rhea-atrace.gz最后一行没有 'TRACE_END'，文件大小也比正常情况下，猜测是多线程情况下写文件出问题了，导致trace无法写入、最后的trace_end也无法写入。
希望作者帮忙看下

**Comment by zeatual** [comment]
也经常遇到这个情况

**Comment by qkmaosjtu** [comment]
> 查看原始文件rhea-atrace.gz最后一行没有 'TRACE_END'，文件大小也比正常情况下，猜测是多线程情况下写文件出问题了，导致trace无法写入、最后的trace_end也无法写入。

可以贴下你的config文件么

**Comment by threeloe** [comment]
也会遇到这个问题，trace就断掉了，配配置是

**Comment by mzule** [comment]
buffersize太小了，可以试一下 2.0.0 版本，当buffer过小时会有提醒。
