### ISSUE TITLE
方法不闭合 did not end

### ISSUE THREAD

**Issue by taaco** [bytedance/btrace#40]
大家做过kotlin协程trace插桩吗？大量的方法不闭合问题怎么处理？

**Comment by qkmaosjtu** [comment]
> 

方便贴下你的原始Trace文件吗？

**Comment by livelitoday** [comment]
我也遇到了，本来以为是抓取时间太短了，多等了一会儿，还是会出现。
可能是有些方法一直没结束？不应该呀？主线程按道理是一次次的dispatchMessage的过程。

**Comment by mzule** [comment]
2.0.0 优化了闭合问题的处理逻辑，闭合问题已经很少了，可以体验下
