### ISSUE TITLE
To remove a permission request :MANAGE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by sunzhibindev** [bytedance/btrace#42]
# rhea_config.py
`ATRACE_APP_GZ_FILE_LOCATION = "/sdcard/Android/data/%s/files/rhea-trace/"`

remove:
 >
      <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
      <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
      <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />

# TraceSwitch.java 

  static File getRheaTraceDir(Context context) {
        final String packageName = context.getPackageName();
        File externalFilesDir;
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.FROYO) {
            externalFilesDir = context.getExternalFilesDir("");
        } else {
            externalFilesDir = new File("sdcard/Android/data/" + packageName + "files");
        }
        return new File(externalFilesDir, "rhea-trace");
    }

# LocalConfigManager.java::createRheaConfig
 @NonNull
    static TraceConfiguration createRheaConfig(Context context) {
        final File rheaTraceDir = TraceSwitch.getRheaTraceDir(context);
        TraceConfiguration traceConfiguration = LocalConfigManager.readConfigFile(rheaTraceDir);
        if (traceConfiguration == null) {
            traceConfiguration = new TraceConfiguration.Builder()
                    .setMainThreadOnly(TraceRuntimeConfig.isMainThreadOnly())
                    .startWhenAppLaunch(TraceRuntimeConfig.isStartWhenAppLaunch())
                    .setATraceBufferSize(TraceRuntimeConfig.getATraceBufferSize())
                    .enableIO(TraceRuntimeConfig.isEnableIO())
                    .enableMemory(TraceRuntimeConfig.isEnableMemory())
                    .enableClassLoad(TraceRuntimeConfig.isEnableClassLoad())
                    .build();
        }
        Log.d(TAG, "trace config: " + traceConfiguration.toString());
        return traceConfiguration;
    }

**Comment by 5peak2me** [comment]
couldn't agree more！
