### ISSUE TITLE
如何赋予权限? 已经在manifest声明并且动态授予了还是不行

### ISSUE THREAD

**Issue by MrDragonForest** [bytedance/btrace#46]
![image](https://user-images.githubusercontent.com/64659314/197505463-33515e4c-8516-4830-be49-31902d3928cf.png)

manifest中已经加入:
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />

**Comment by sunzhibindev** [comment]
看一下这个，是否对你有帮助 https://github.com/bytedance/btrace/issues/42

**Comment by mzule** [comment]
2.0.0 已经不再需要存储权限
