### ISSUE TITLE
Windows & RheaTrace 踩坑日记

### ISSUE THREAD

**Issue by HenryWu01** [bytedance/btrace#51]
写了一点关于 Windows 和 BTrace 的踩坑日记，希望可以帮助大家少走一些弯路。

## 1. 运行 rheatrace.py 报错: ``IOError: [Errno 22] invalid mode ('a') or filename:``
> 错误原因: Windows 中文件名不能含有 ``:`` 等特殊字符

在 **rhea_logger.py** 文件中 
```Python
fh = logging.FileHandler(r'{0}/_log_{1}.log'.format(output_dir, time.strftime("%Y-%m-%d-%H:%M:%S", time.localtime()), encoding='utf-8'))
```
修改为
```Python
fh = logging.FileHandler(r'{0}/_log_{1}.log'.format(output_dir, str(int(time.time())), encoding='utf-8'))
```

## 2. 运行 rheatrace.py 过程中, 调用 ``systrace`` 报错: ``subprocess.Popen WindowsError: [Error 2]``
> 报错原因: Windows 安装 Python 2.7 之后的可执行文件名为 ``python.exe`` 而不是 ``python2.7.exe``

在 **systrace_capturer.py** 文件中
```Python
cmd = ["python2.7", systrace_path]
```
修改为
```Python
cmd = ["python", systrace_path]
```

P.S: 如果你有Python 3 可以将 Python 2.7 的可执行文件改名为 ``python2.exe`` 然后将以上命令修改为
```Python
cmd = ["python2", systrace_path]
```

## 3. 运行过程中提示 ``Unfortunately, start trace failed`` 或者 ``failed to write rhea-atrace.gz file completely``
> 报错原因: 无法创建文件和文件夹 (无权限)

在 app 目录下的 **AndroidManifest.xml`` 中声明以下权限:
```Xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
```

然后通过权限请求库例如 ``XXPermissions`` 进行动态申请:
```Java
XXPermissions.with(this)
    .permission(Manifest.permission.MANAGE_EXTERNAL_STORAGE)
    .request(new OnPermissionCallback() {
        @Override
        public void onGranted(@NonNull List<String> permissions, boolean all) {
            
        }
    });
```

重新打开软件后 Toast 消失, 运行 rheatrace.py 无错误提示

## 4. 运行 rheatrace.py 过程中, 调用 ``gzip`` 报错: ``subprocess.Popen WindowsError: [Error 2]``
> 报错原因: Windows 下没有 gzip 程序

在 [Gzip for Windows 网页](https://gnuwin32.sourceforge.net/packages/gzip.htm) 下载 gzip 并添加到 ``PATH`` 环境变量后**重新打开命令行**运行 rheatrace.py 即可

**Comment by livelitoday** [comment]
哥们你在windows上跑通了是吗

**Comment by HenryWu01** [comment]
> 哥们你在windows上跑通了是吗

是的，遇到的问题我上面基本都有记录

**Comment by livelitoday** [comment]
> > 哥们你在windows上跑通了是吗
> 
> 是的，遇到的问题我上面基本都有记录

搞好之后，是实际项目中，会有那种“Did not end“的问题吗。

**Comment by mzule** [comment]
2.0.0 已经支持 Windows了
