### ISSUE TITLE
为什么插桩的时候，开始和结束都是beginSection

### ISSUE THREAD

**Issue by JuneLeo** [bytedance/btrace#52]
```java
 /**
     * the method would be injected in the enter of app methods.
     *
     * @param methodId method id.
     */
    public static void i(String methodId) {
        RheaTrace.t(methodId);
    }

    /**
     * the method would be injected in the exits of app methods.
     *
     * @param methodId method id.
     */
    public static void o(String methodId) {
        RheaTrace.t(methodId);
    }
```
```java
static void t(String methodId) {
        if (!isMainProcess) {
            return;
        }
        if (mainThreadOnly) {
            if (Thread.currentThread() == sMainThread) {
                Trace.beginSection(methodId);
            }
        } else {
            Trace.beginSection(methodId);
        }
    }
```

**Comment by JuneLeo** [comment]
![image](https://user-images.githubusercontent.com/22164576/209951792-2ef7be4e-fdae-406c-b0da-5fe92b008233.png)
你们hook了atrace_begin_body和atrace_end_body 可能是写入到了你们自己的文件中了

**Comment by livelitoday** [comment]
我也没弄明白，看了他们的博客，写的是：
<img width="861" alt="image" src="https://user-images.githubusercontent.com/18246867/212786520-a91ae836-e88d-4c9f-b0cc-79f4ab93062f.png">

**Comment by mzule** [comment]
是的，我们写入自己的文件了。我们是通过 methodId 字符串开始的 B: 或者 E: 来区分开始与结束的。

如果直接使用系统的 beginSection 和 endSection，可能因为隐式的或者显式的抛出异常，导致部分 endSection 不会被执行到，进而导致 trace 错乱，因为 endSection 没有方法信息，我们也无法知道是哪里的 endSection 未执行。

所以，我们统一通过 beginSection 记录 trace，通过名称的 B: 或者 E: 来区分，这样可以在 B 或者 E 都记录下方法信息，我们可以算法补齐部分缺少 E 的方法。
