### ISSUE TITLE
为什么给方法插桩的代码开始和结束都是Trace.beginSection()?

### ISSUE THREAD

**Issue by livelitoday** [bytedance/btrace#58]
<img width="878" alt="image" src="https://user-images.githubusercontent.com/18246867/222597187-f251022d-f555-4e5a-b93d-236fe5830c9c.png">

<img width="677" alt="image" src="https://user-images.githubusercontent.com/18246867/222597479-046c3da4-f54c-48d2-a45e-82a2125401ec.png">

<img width="578" alt="image" src="https://user-images.githubusercontent.com/18246867/222597618-9c3c2e74-b5c5-4ad6-a9d5-7232c3a28407.png">

**Comment by mzule** [comment]
![image](https://user-images.githubusercontent.com/2096572/226515976-6357bdf2-2224-4349-a51c-4cbc6d4e9323.png) 参考这个图片，我们是通过 methodId 字符串开始的 B: 或者 E: 来区分开始与结束的。

如果直接使用系统的 beginSection 和 endSection，可能因为隐式的或者显式的抛出异常，导致部分 endSection 不会被执行到，进而导致 trace 错乱，因为 endSection 没有方法信息，我们也无法知道是哪里的 endSection 未执行。

所以，我们统一通过 beginSection 记录 trace，通过名称的 B: 或者 E: 来区分，这样可以在 B 或者 E 都记录下方法信息，我们可以算法补齐部分缺少 E 的方法。
