### ISSUE TITLE
Can't find systrace in environment path 

### ISSUE THREAD

**Issue by ivalimmb** [bytedance/btrace#6]
如图 正常-v可以用  但是第二天命令就不行了  是什么原因呢？
环境：Mac m1   Python 2.7.18 (default, Oct  2 2021, 04:20:38)

mmb@mmbdeMac-mini rheatrace % python rheatrace.py -v
Current version is 1.0.1.
mmb@mmbdeMac-mini rheatrace % python rheatrace.py -a rhea.sample.android -t 5 -o ./output/mynewtrace.html sched freq
Can't find systrace in environment path 

如下systrace 也是正常使用
python systrace.py --time=10 -o mynewtrace.html gfx

**Comment by kissonchan** [comment]
> 如图 正常-v可以用 但是第二天命令就不行了 是什么原因呢？ 环境：Mac m1 Python 2.7.18 (default, Oct 2 2021, 04:20:38)
> 
> mmb@mmbdeMac-mini rheatrace % python rheatrace.py -v Current version is 1.0.1. mmb@mmbdeMac-mini rheatrace % python rheatrace.py -a rhea.sample.android -t 5 -o ./output/mynewtrace.html sched freq Can't find systrace in environment path
> 
> 如下systrace 也是正常使用 python systrace.py --time=10 -o mynewtrace.html gfx

重新执行  source ~/.bash_profile。mac 系统的原因。
