### ISSUE TITLE
渲染详情采集能力实现疑问请教

### ISSUE THREAD

**Issue by zefengsysu** [bytedance/btrace#64]
渲染详情采集能力记录 RenderNode 的 prepare 的实现上，我理解是先尝试 InlineHook RenderNode::prepareTreeImpl，Hook 失败的情况会尝试 InlineHook SkiaDisplayList::prepareListAndChildren，然后通过改写传入的 childFn 参数对应的虚表中 operator() 的函数指针的方式来替换实际会被调用到的 childFn 。我本地测试了下，鸿蒙测试机上确实走到了这个兜底路径，而且改写虚表的操作是生效的。这里有几个疑问想请教下大佬们，
1. 为啥这里 std::function 的 operator() 函数指针实际会记录在虚表上，我理解操作符重载的情况实现上实际应该不需要走运行时的动态派发，C++ 编译器的实现应该是不需要将其记录到虚表上的？
2. 这里对应的虚表索引 STD_FUNCTION_CALL_OPERATOR_VIRTUAL_INDEX  具体是怎么确认的？

**Comment by WangFeng-AHU** [comment]
1. std::function 的实现走的还是虚函数的动态派发，只不过包装了两层，最终调用到的是 __base::operator()(...) 虚函数上的，所以可以替换虚函数表中的函数指针；
2. 虚函数指针在虚函数表中的位置顺序是和类中虚函数的声明顺序保持一致的，因此可以根据头文件中函数声明顺序来计算，另外虚析构函数占两个位置（有两个），参考 http://itanium-cxx-abi.github.io/cxx-abi/abi.html#vtable

**Comment by zefengsysu** [comment]
> 1. std::function 的实现走的还是虚函数的动态派发，只不过包装了两层，最终调用到的是 __base::operator()(...) 虚函数上的，所以可以替换虚函数表中的函数指针；
> 2. 虚函数指针在虚函数表中的位置顺序是和类中虚函数的声明顺序保持一致的，因此可以根据头文件中函数声明顺序来计算，另外需要注意的虚析构函数有两个，在虚表中占两个位置，参考 http://itanium-cxx-abi.github.io/cxx-abi/abi.html#vtable

感谢大佬解答，理解了。实际上不是std::function的operator()是虚函数，是最终调到的__base的operator()是虚函数。
