### ISSUE TITLE
编译错误(依赖冲突)

### ISSUE THREAD

**Issue by BinarySatan** [bytedance/btrace#68]
Circular dependency between the following tasks:
:app:compileDebugJavaWithJavac
+--- :app:dataBindingExportBuildInfoDebug

|    \--- :app:generateDebugSources
|         \--- :app:generateDebugPresetMap
|              \--- :app:mergeDebugAssets
|                   \--- :app:copyRheaDebugMapping
|                        \--- :app:dexBuilderDebug
|                             \--- :app:transformClassesWithSafeCodeTransformForDebug
|                                  \--- :app:transformClassesWithStringFogForDebug
|                                       \--- :app:transformClassesWithBoosterForDebug
|                                            \--- :app:transformClassesWithRheaTraceForDebug
|                                                 \--- :app:transformClassesWithActivityAliasForLunaForDebug
|                                                      \--- :app:transformClassesWithActivityAliasForCeresForDebug
|                                                           \--- :app:compileDebugJavaWithJavac (*)
\--- :app:generateDebugPresetMap (*)

Gradle版本: 6.8.3
AGP版本: 4.0.2
brace: 2.0.0

开了databinding

**Comment by mzule** [comment]
可以看下readme的已知问题，有描述这个情况。
