### ISSUE TITLE
traceWithMethodID may not actually take effect

### ISSUE THREAD

**Issue by xiangtailiang** [bytedance/btrace#70]
I noticed that the traceWithMethodID method in com/bytedance/rheatrace/plugin/extension/TraceCompilation.kt is actually not being used in the code, so setting the switch may not actually take effect.

===
我注意到com/bytedance/rheatrace/plugin/extension/TraceCompilation.kt 里面的traceWithMethodID，实际上是没有代码使用，所以这个开关设置后其实是不生效的？

**Comment by mzule** [comment]
这是1.0的遗留参数，已经废弃了，后面会下掉。
