### ISSUE TITLE
非必现类名或方法名出现unknown的情况

### ISSUE THREAD

**Issue by renzhenming** [bytedance/btrace#78]
修改代码后直接运行项目，然后开启btrace抓启动的trace信息过程中出现

<img width="370" alt="企业微信截图_16888041672852" src="https://github.com/bytedance/btrace/assets/16622940/70548d64-1ed1-4c2a-a775-36b992745e3d">

**Comment by mzule** [comment]
我们也发现了这个问题，应该是增量编译对于内置mapping缓存的处理有点问题，建议clean项目重新编译

**Comment by mzule** [comment]
预计下次发布修复。
