### ISSUE TITLE
java.lang.UnsupportedOperationException: NestMember requires ASM7

### ISSUE THREAD

**Issue by fanzhouyou** [bytedance/btrace#82]
正常打包没问题，添加了BTrace之后打包失败
提示java.lang.UnsupportedOperationException: NestMember requires ASM7
build//ByteX/RheaTraceForSs2Debug/rheaTrace/rheaTrace_log.txt如下
[rheaTrace_log.txt](https://github.com/bytedance/btrace/files/12036202/rheaTrace_log.txt)

**Comment by itcayman** [comment]
我也遇到了，求大神解答

**Comment by mzule** [comment]
已经更新了新版本，试试readme的最新版本
