### ISSUE TITLE
Error: Only 4311864 of the 10796954 methods are resolved the method name.

### ISSUE THREAD

**Issue by AriesJiang** [bytedance/btrace#86]
执行命令：
java -jar rhea-trace-shell.jar -a com.kugou.fanxing -t 10 -mode simple -o output.pb rhea.all sched -fullClassName
异常：
07-17 12:00:36.927 E RheaTrace : Error: Only 4311864 of the 10796954 methods are resolved the method name.
07-17 12:00:36.927 E RheaTrace :  Tips: Please check whether the @CriticalNative annotation is filtered when packaging.
请问是哪里配置不正确？

**Comment by PTrainbow** [comment]
> 执行命令： java -jar rhea-trace-shell.jar -a com.kugou.fanxing -t 10 -mode simple -o output.pb rhea.all sched -fullClassName 异常： 07-17 12:00:36.927 E RheaTrace : Error: Only 4311864 of the 10796954 methods are resolved the method name. 07-17 12:00:36.927 E RheaTrace : Tips: Please check whether the @CriticalNative annotation is filtered when packaging. 请问是哪里配置不正确？

如果有：reuse cached mapping  xxxxx  这行信息
把那个 mapping 删掉

**Comment by mzule** [comment]
这可能是增量编译的bug，可以clean后再编译试试，也可以升级到最新版本。
