### ISSUE TITLE
Help with license

### ISSUE THREAD

**Issue by vchhasatia** [bytedance/btrace#99]
Hello btrace team,

I am confused by license text in two of the files. Can you please provide reason behind re-licensing LGPL 2.1 files to Apache 2.0?

https://github.com/bytedance/btrace/blob/master/rhea-build/rhea-build-common/src/main/java/com/bytedance/rheatrace/common/utils/ClassToJavaFormat.kt
https://github.com/bytedance/btrace/blob/master/rhea-build/rhea-build-common/src/main/java/com/bytedance/rheatrace/common/utils/JavaToClassFormat.kt

**Comment by xiaomahuang** [comment]
> Hello btrace team,
> 
> I am confused by license text in two of the files. Can you please provide reason behind re-licensing LGPL 2.1 files to Apache 2.0?
> 
> https://github.com/bytedance/btrace/blob/master/rhea-build/rhea-build-common/src/main/java/com/bytedance/rheatrace/common/utils/ClassToJavaFormat.kt https://github.com/bytedance/btrace/blob/master/rhea-build/rhea-build-common/src/main/java/com/bytedance/rheatrace/common/utils/JavaToClassFormat.kt

Thank you for your feedback. We will address the related issues as soon as possible. This area was overlooked by the relevant team member in terms of licensing. We appreciate your feedback immensely.
